services:
  db:
    image: mongo:6.0.13
    volumes:
      - mongo_data:/data/db
    networks:
      - db-network
  backend:
    build:
      context: ./backend
      target: production
    networks:
      - app-network
      - db-network
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      target: production
    networks:
      - app-network
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - backend
      - frontend
networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge
volumes:
  mongo_data:
