services:
  db:
    image: mongo:6.0.13
    volumes:
      - mongo_data:/data/db
    networks:
      - db-network
  backend:
    build:
      context: ./backend
      target: production
    networks:
      - app-network
      - db-network
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    networks:
      - app-network
    ports:
      - "8080:80"
    depends_on:
      - backend
networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge
volumes:
  mongo_data:
